server:
  port: 8888
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.14.147.139:3306/example?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=true
    username: root
    password: zhongyua
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    date-format: yyyy-MM-dd