spring:
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  profiles:
    active: develop # produce生产环境 develop开发环境
datasource:
  druid:
    url: jdbc:mysql://127.0.0.1:3306/springboot?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=true
    username: root
    password: 123456
    initialSize: 10
    maxActive: 100
    maxWait: 60000
    minIdle: 5
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zhongyu.bean
  check-config-location: true
  config-location: classpath:config/mybatis.xml